#:kivy 1.0

<ChooseGame@MDBoxLayout>:
    orientation: 'vertical'
    padding: ['40sp', '40sp']
    spacing: '10sp'
    Header:
        text: '請選擇遊戲'
    MDBoxLayout:
        adaptive_height: True
        padding: ['60sp', '20sp']
        spacing: '10sp'
        GameButton:
            text: '今彩539'
        GameButton:
            text: '大樂透'
    NextStep:

<GameButton>:
    group: 'game'
    font_size: '16sp'
    font_name: 'font/Noto_Sans_TC/NotoSansTC-Bold.otf'
